version: '3.8'
services:
  gateway:
    build: gateway/
    image: shareit-gateway-image
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
      - db
    environment:
      - SERVER_PORT=8080
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server/
    image: shareit-server-image
    container_name: shareit-server
    #    ports:
    #      - "9090:9090"
    depends_on:
      - db
    environment:
      - SERVER_PORT=9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres


  db:
    image: postgres:13.7-alpine
    container_name: shareit-db
    volumes:
      - /var/lib/postgresql/data/
      - ./server/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    #    ports:
    #      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres